version: '3'

services:
    pocrabbit:
        container_name: pocrabbit
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            - "5000:80"
            - "443:443"
        depends_on: 
            - "rabbitmq"
    
    rabbitmq:
        container_name: localrabbitpoc
        image: rabbitmq:3-management
        restart: always
        ports: 
            - "5672:5672"
            - "15672:15672"
        environment: 
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin